version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 10...
      - curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Testing...
      - npm test -- --watchAll=false
      - echo Building...
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist
