const CONDITIONS = {
  '01d': {
    color: 'white',
    image: 'clear-sky-paris',
    icon: '01d',
    large: '1vZfSWJ',
    small: '4N6HxcD',
  },
  '02d': {
    color: 'yellow',
    image: 'few-clouds-grass',
    icon: '02d',
    large: 'QQTjqk2',
    small: 'TLWPB94',
  },
  '03d': {
    color: 'gold',
    image: 'scattered-clouds-sun',
    icon: '03d',
    large: 'Vp0Sn2X',
    small: '1fwLqq7',
  },
  '04d': {
    color: 'orange',
    image: 'broken-clouds-sunset',
    icon: '04d',
    large: '5MDn8BX',
    small: '0rgH8Px',
  },
  '09d': {
    color: 'peach',
    image: 'rain-shower-london',
    icon: '90d',
    large: 'BtDhZn4',
    small: 'RpwYNzV',
  },
  '10d': {
    color: 'blue',
    image: 'rain-ground',
    icon: '10d',
    large: 'Qd6ZmVj',
    small: 'D4Vvt0K',
  },
  '11d': {
    color: 'purple',
    image: 'thunder-storm-sydney',
    icon: '11d',
    large: 'sCwJZM9',
    small: 'DMH6W6g',
  },
  '13d': {
    color: 'light-purple',
    image: 'snow-space-needle',
    icon: '13d',
    large: 'mC2jdW1',
    small: 'fv3WGSv',
  },
  '50d': {
    color: 'aquamarine',
    image: 'mist-golden-gate',
    icon: '50d',
    large: 'QmCmQMR',
    small: 'N66BLVC',
  },
  '01n': {
    color: 'white',
    image: 'clear-sky-paris',
    icon: '01n',
    large: '1vZfSWJ',
    small: '4N6HxcD',
  },
  '02n': {
    color: 'yellow',
    image: 'few-clouds-grass',
    icon: '02n',
    large: 'QQTjqk2',
    small: 'TLWPB94',
  },
  '03n': {
    color: 'gold',
    image: 'scattered-clouds-sun',
    icon: '03n',
    large: 'Vp0Sn2X',
    small: '1fwLqq7',
  },
  '04n': {
    color: 'orange',
    image: 'broken-clouds-sunset',
    icon: '04n',
    large: '5MDn8BX',
    small: '0rgH8Px',
  },
  '09n': {
    color: 'peach',
    image: 'rain-shower-london',
    icon: '90n',
    large: 'BtDhZn4',
    small: 'RpwYNzV',
  },
  '10n': {
    color: 'blue',
    image: 'rain-ground',
    icon: '10n',
    large: 'Qd6ZmVj',
    small: 'D4Vvt0K',
  },
  '11n': {
    color: 'purple',
    image: 'thunder-storm-sydney',
    icon: '11n',
    large: 'sCwJZM9',
    small: 'DMH6W6g',
  },
  '13n': {
    color: 'light-purple',
    image: 'snow-space-needle',
    icon: '13n',
    large: 'mC2jdW1',
    small: 'fv3WGSv',
  },
  '50n': {
    color: 'aquamarine',
    image: 'mist-golden-gate',
    icon: '50n',
    large: 'QmCmQMR',
    small: 'N66BLVC',
  },
};

export default CONDITIONS;
